import React from 'react';
import PropTypes from 'prop-types';
import { PrimaryButton as PrimaryButtonOF } from '@fluentui/react';
import pickWithValues from "usr/a_lib/utils/pickWithValues";

export interface PrimaryButtonProps {
  allowDisabledFocus?: boolean;
  text: string;
  onClick?: () => void;
}

/**
 * Button is generated by Webcodesk. Replace this comment with a valuable description.
 */
class PrimaryButton extends React.Component<PrimaryButtonProps, any> {

  static propTypes: PropTypes.InferProps<PrimaryButtonProps> = {
    /**
     * Whether the button can have focus in disabled mode
     */
    allowDisabledFocus: PropTypes.bool,
    /**
     * Label of the button.
     */
    text: PropTypes.string.isRequired,
    /**
     * Triggered when the user clicks on the button
     */
    onClick: PropTypes.func,
  };

  static defaultProps: PrimaryButtonProps = {
    text: 'Button',
  };

  // constructor(props: PrimaryButtonProps) {
  //   super(props);
  // }

  handleButtonClick = (e: React.MouseEvent<HTMLElement>): void => {
    if (e) {
      e.stopPropagation();
      e.preventDefault();
    }
    if (this.props.onClick) {
      this.props.onClick();
    }
  };

  render() {
    const {
      allowDisabledFocus,
      text
    } = this.props;
    const properties = pickWithValues({allowDisabledFocus, text});
    return (
        <PrimaryButtonOF
            {...properties}
            onClick={this.handleButtonClick}
        />
    );
  }
}

export default PrimaryButton;
