import React from 'react';
import PropTypes from 'prop-types';
import { PrimaryButton } from 'office-ui-fabric-react';

interface ButtonProps {
  text: string,
}

/**
 * Button is generated by Webcodesk. Replace this comment with a valuable description.
 */
class Button extends React.Component<ButtonProps, any> {

  static propTypes: any = {
    /**
     * Label of the button.
     */
    text: PropTypes.string.isRequired,
  };
  static defaultProps: ButtonProps = {
    text: 'Button',
  };

  constructor(props: ButtonProps) {
    super(props);
    // const { inputText, styling } = this.props;
    // this.state = {
    //   prevStyling: styling,
    //   rootStyle: { ...styling, ...styles.root },
    //   localInputText: inputText || ''
    // };
  }

  handleButtonClick = (e: React.MouseEvent<HTMLElement>): void => {
    if (e) {
      e.stopPropagation();
      e.preventDefault();
    }
    alert('test');
  };

  render() {
    return (
        <PrimaryButton text={this.props.text} onClick={this.handleButtonClick} />
    );
  }
}

export default Button;
